// Runs the same importer the demo uses, over the bundled fixtures, and writes
// the published registers data/events.json and data/places.json.
// These files are generated: never edit them by hand. The demo app also re-runs
// the import in the browser each day, because fixture dates are relative to today.
import fs from 'node:fs';
import { runImport } from '../site/src/import-job.js';

const root = new URL('../site/', import.meta.url);
const read = (p) => JSON.parse(fs.readFileSync(new URL(`data/${p}`, root), 'utf8'));
const fetchText = async (p) => fs.readFileSync(new URL(p.replace(/^\//, ''), root), 'utf8');
const now = new Date();
const reg = await runImport({ sources: read('sources.json'), tags: read('tags.json'), manualEvents: read('manual-events.json'), now, fetchText });
const header = { generatedAt: reg.generatedAt, generatedBy: 'scripts/import.mjs', note: 'Generated by the importer from demo fixtures. Do not edit by hand.' };
fs.writeFileSync(new URL('data/events.json', root), JSON.stringify({ ...header, health: reg.health, events: reg.events }, null, 1) + '\n');
fs.writeFileSync(new URL('data/places.json', root), JSON.stringify({ ...header, places: reg.places }, null, 1) + '\n');
console.log(`events: ${reg.events.length} (from ${Object.values(reg.health).reduce((s, h) => s + (h.rows || 0), 0)} source rows), places: ${reg.places.length}`);
for (const [id, h] of Object.entries(reg.health)) console.log(' ', id, JSON.stringify(h));
